pipeline {
    agent {
        node {
            label 'Agent-1'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 1, unit: 'MINUTES') 
    }
    stages {
        stage('Build') {
            steps {
                script{
                    sh """
                        echo "building"
                        echo $COURSE
                        sleep 5
                        env
                    """
                }
            }
        }
        stage('Test') {
            steps {
                script{
                    sh """
                        echo "building"
                    """
            }
        }
    }
        stage('Deploy') {
            steps {
                script{
                    sh """
                        echo "building"
                    """
                }
            }
        }
    }
    post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo ' I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}